Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "henkaouaS" do |controller|
    controller.vm.hostname = "henkaouaS"
    controller.vm.network "private_network", ip: "192.168.56.110"
    controller.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end

    controller.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -
      curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
      mkdir -p ~/.kube
      sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      sudo chown $(id -u):$(id -g) ~/.kube/config
    SHELL
  end

  config.vm.define "henkaouaSW" do |worker|
    worker.vm.hostname = "henkaouaSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
    worker.vm.provision "shell", inline: <<-SHELL
      # Install K3s in agent mode, pointing to the controller node
      K3S_URL=https://192.168.56.110:6443
      K3S_TOKEN=$(ssh vagrant@192.168.56.110 sudo cat /var/lib/rancher/k3s/server/node-token)
      curl -sfL https://get.k3s.io | K3S_URL=$K3S_URL K3S_TOKEN=$K3S_TOKEN sh -

      # Install kubectl
      curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
    SHELL
  end
end
